name: Deploy to VPS (Docker build on server)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PASSKEY}}
          script: |
            set -e
            cd ${{ secrets.REPO_DIR }}
            git fetch origin main
            git reset --hard origin/main
            docker compose up -d --build
            docker image prune -f